### ISSUE TITLE
Drag to trigger calculator does not works

### ISSUE THREAD

**Issue by franckgaga** [iamkroot/asus-numpad#2]
Hi, 

Thanks for sharing your work!

I tried all the possible drag movement and the calculator does not show
I'm using a Zenbook UX425EA running Pop!_OS 21.10 (same calculator app as Ubunutu)
It does works on windows 10 (by dragging from-top left to top-right of the mousepad)

**Comment by iamkroot** [comment]
The drag to trigger calc feature is currently being re-written. So it might be better to wait for the next release to try it.

## How to Debug
1. You need to get the debug build of `asus-numpad` in order to enable logging. For now, this means you'll need to install the Rust toolchain (https://rustup.rs), since I'm not providing pre-built debug binaries.
2. Once you have the Rust toolchain installed, you can run `sudo -E cargo install --root /usr --git="https://github.com/iamkroot/asus-numpad" --tag=v0.3.0 --debug` to install the debug version.
3. To run with debug logs, run `RUST_LOG=debug asus-numpad --layout=...`

**Comment by iamkroot** [comment]
I've released `v0.4`, and also uploaded the debug version so you that wouldn't have to build it manually.
Keep in mind that the installation instructions have changed, so you might want to start from a clean slate.
Once installed, just try step 3 from previous comment to start printing debug logs. If you can't figure out what the issue is, paste the logs here.

**Comment by iamkroot** [comment]
Hmm before all this, try the following:
* You need to set the `Calc` key shortcut in your system's preferences.
* Meaning, the system has to be configured to start the calculator when you press the key on your keyboard.
* Try this [answer](https://askubuntu.com/a/1106172/797109).

Or, with the latest version, you can specify `gnome-calculator` as your `calc_start_command`.

**Comment by franckgaga** [comment]
I've just noticed that it does work with my version (v0.3) but only when the when the numpad is off. Is it possible to make the drag movement works also when the numpad is on (light on) ?

Thanks !

**Comment by iamkroot** [comment]
Not really, that would conflict with the "tap calc button to change brightness" gesture. I think the Windows driver also behaves similarly.

**Comment by franckgaga** [comment]
That's a good point. I'm not sure about the Windows drive. I will uninstall v0.3, install 0.4 and give you a feedback soon.

Thanks

**Comment by franckgaga** [comment]
Installed v0.4 and everything work as intended, calculator included, thanks !

**Comment by iamkroot** [comment]
> Is it possible to make the drag movement works also when the numpad is on (light on) ?

I revisited the code and it was fairly simple to support this feature. The nuance was that brightness is changed when you _hold_ the calc button, so it is ok to allow the drag gesture. (Windows behaves the same way).

Will be released in the next version.

**Comment by franckgaga** [comment]
@iamkroot I'm trying to map <kbd>SUPER</kbd>+<kbd>Q</kbd> on `calc_stop_command` (that closes the window on pop_os). it does not close the calc window. Is my configuration seems ok to you :
```
calc_stop_command = ["KEY_LEFTMETA","KEY_Q"]
```
Thanks for your help!

**Comment by iamkroot** [comment]
The keys seem to be correct at least. But Linux DEs usually have trouble dealing with shortcuts with the Meta key, especially when trying to generate them from a non-physical keyboard.

If you were on KDE, I'd say there is a way to bypass the shortcut and directly use QDBUS to run the "close window" command. I'm not too well versed with GNOME to know if there's an equivalent for that. Nevertheless, [here's](https://www.linuxjournal.com/article/10455) an article that explains how to discover if there's a way to do it using DBUS.

Another option might be to set the stop command to something like `pkill __calculate_exec_name__` (where the name is whatever pop_os uses as calc), using variant b in the config description. That way, if the calc is open, it'll get killed.
