### ISSUE TITLE
ASUS Dial (Dialpad)

### ISSUE THREAD

**Issue by den0620** [iamkroot/asus-numpad#21]
Any plans on implementing dialpad? I have Vivobook Pro 14X OLED and asus-numpad works perfectly except it lights as dial, not numpad (for obvious reasons)

**Comment by iamkroot** [comment]
That looks likes a completely different style of interaction (very slick!) 

I believe it will be better to implement this in a separate repo, since it won't be sharing most of the state tracking code we have here for the numpad.

It would be nice to see this working in Linux, but I do not have access to the laptop, nor the time to code it up for now. If someone is willing to contribute, I can review/guide a PR.
